# Generated by Django 5.2 on 2025-04-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_message_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='content',
            field=models.TextField(help_text='The main body of the message', verbose_name='Message'),
        ),
    ]
