# Generated by Django 5.2 on 2025-05-12 10:58

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('full_name', models.CharField(max_length=100)),
                ('nin_number', models.CharField(help_text='Enter your 14-digit National ID Number', max_length=14, unique=True, verbose_name='National Identification Number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=15)),
                ('dob', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1))], verbose_name='Date of Birth')),
                ('place_of_birth', models.CharField(max_length=100)),
                ('current_address', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=100)),
                ('place_of_work', models.CharField(max_length=100)),
                ('next_of_kin_name', models.CharField(max_length=100)),
                ('next_of_kin_email', models.EmailField(max_length=254)),
                ('next_of_kin_phone', models.CharField(max_length=15)),
                ('next_of_kin_professional', models.CharField(max_length=100)),
                ('time_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
