# Generated by Django 5.2 on 2025-05-14 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nin_number',
            field=models.CharField(help_text='Enter your 14-digit National ID Number', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='NIN must be exactly 14 characters, consisting of letters and numbers.', regex='^[A-Za-z0-9]{14}$')], verbose_name='National Identification Number'),
        ),
    ]
