# Generated by Django 5.2 on 2025-05-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_nin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='youth-connect.png', upload_to='profile_pics/'),
        ),
    ]
