# Generated by Django 5.2 on 2025-06-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='ids/user/back/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='ids/user/front/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kin_id_back',
            field=models.ImageField(blank=True, null=True, upload_to='ids/kin/back/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kin_id_front',
            field=models.ImageField(blank=True, null=True, upload_to='ids/kin/front/'),
        ),
    ]
