# Generated by Django 5.2 on 2025-04-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nin_number', models.CharField(max_length=14, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('current_address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('professional', models.CharField(max_length=255)),
                ('place_of_work', models.CharField(max_length=255)),
                ('time_joined', models.DateField()),
                ('next_of_kin_name', models.CharField(max_length=255)),
                ('next_of_kin_email', models.EmailField(max_length=254)),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('next_of_kin_professional', models.CharField(max_length=255)),
            ],
        ),
    ]
