# Generated by Django 5.2 on 2025-04-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the member', max_length=255)),
                ('nin_number', models.CharField(help_text='National Identification Number (must be 14 characters)', max_length=14, unique=True)),
                ('gender', models.CharField(help_text='Gender of the member', max_length=20)),
                ('age', models.IntegerField(help_text='Age of the member')),
                ('marital_status', models.CharField(help_text='Marital status of the member', max_length=20)),
                ('dob', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('place_of_birth', models.CharField(help_text='Place of birth', max_length=255)),
                ('current_address', models.TextField(help_text='Current residential address')),
                ('email', models.EmailField(help_text='Email address for communication and authentication', max_length=254, unique=True)),
                ('signature', models.CharField(blank=True, help_text='Optional signature data', max_length=100, null=True)),
                ('professional', models.CharField(help_text='Professional field of the member', max_length=255)),
                ('place_of_work', models.CharField(help_text='Workplace name', max_length=255)),
                ('time_joined', models.DateTimeField(blank=True, help_text='Timestamp when the member joined the system', null=True)),
                ('next_of_kin_name', models.CharField(help_text='Full name of the next-of-kin', max_length=255)),
                ('next_of_kin_email', models.EmailField(help_text='Email address of the next-of-kin', max_length=254)),
                ('next_of_kin_phone', models.CharField(help_text='Phone number of the next-of-kin', max_length=20)),
                ('next_of_kin_professional', models.CharField(help_text='Profession of the next-of-kin', max_length=255)),
                ('otp', models.CharField(blank=True, help_text='Generated OTP for email verification', max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, help_text='Timestamp when the OTP was created', null=True)),
                ('otp_attempts', models.PositiveIntegerField(default=0, help_text='Tracks the number of failed OTP attempts')),
                ('is_verified', models.BooleanField(default=False, help_text="Indicates whether the member's email is verified")),
                ('is_locked', models.BooleanField(default=False, help_text='Indicates if the account is temporarily locked')),
                ('lock_until', models.DateTimeField(blank=True, help_text='The timestamp until the account remains locked', null=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
