# Generated by Django 5.2 on 2025-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_alter_member_options_member_is_verified_member_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
