# Generated by Django 5.2 on 2025-04-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_member_is_locked_member_lock_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
