# Generated by Django 5.2 on 2025-04-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_alter_member_otp_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='otp_attempts',
        ),
    ]
