# Generated by Django 5.2 on 2025-04-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_remove_member_otp_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sender', max_length=255)),
                ('email', models.EmailField(help_text='Email of the sender', max_length=254)),
                ('content', models.TextField(help_text='Message content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was submitted')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(help_text='Age of the member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='current_address',
            field=models.TextField(help_text='Current residential address'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(help_text='Email for communication and authentication', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(help_text='Full name of the member', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(help_text='Gender of the member', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether the account is temporarily locked'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verification status of the member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lock_until',
            field=models.DateTimeField(blank=True, help_text='Time until the lock is lifted', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(help_text='Marital status', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='next_of_kin_email',
            field=models.EmailField(help_text='Email of next-of-kin', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='next_of_kin_name',
            field=models.CharField(help_text='Full name of next-of-kin', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='next_of_kin_phone',
            field=models.CharField(help_text='Phone number of next-of-kin', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='next_of_kin_professional',
            field=models.CharField(help_text='Profession of next-of-kin', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='nin_number',
            field=models.CharField(help_text='National Identification Number', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='otp',
            field=models.CharField(blank=True, help_text='Generated OTP for verification', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when OTP was generated', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='place_of_birth',
            field=models.CharField(help_text='Place of birth', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='place_of_work',
            field=models.CharField(help_text='Workplace name', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='professional',
            field=models.CharField(help_text='Professional field of the member', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='signature',
            field=models.CharField(blank=True, help_text='Optional signature data', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='time_joined',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the member joined', null=True),
        ),
    ]
