# Generated by Django 5.2 on 2025-04-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='leaders/'),
        ),
    ]
